# Generated by Django 4.2.4 on 2023-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='visible',
            field=models.BooleanField(default=False, max_length=250),
        ),
    ]
