export interface Product {
  id: number,
  name: string,
  category: string,
  description: string,
  visible: boolean,
  image: string,
}

//
// export const products = [
//   {
//     id: 1,
//     name: "Item 1",
//     category: "Category A",
//     description: "This is the description for Item 1.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 2,
//     name: "Item 2",
//     category: "Category B",
//     description: "This is the description for Item 2.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 3,
//     name: "Item 3",
//     category: "Category A",
//     description: "This is the description for Item 3.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 4,
//     name: "Item 4",
//     category: "Category C",
//     description: "This is the description for Item 4.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 5,
//     name: "Item 5",
//     category: "Category B",
//     description: "This is the description for Item 5.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 6,
//     name: "Item 6",
//     category: "Category A",
//     description: "This is the description for Item 6.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 7,
//     name: "Item 7",
//     category: "Category D",
//     description: "This is the description for Item 7.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
//   {
//     id: 8,
//     name: "Item 8",
//     category: "Category A",
//     description: "This is the description for Item 8.",
//     visible: true,
//     image: "https://img.freepik.com/premium-photo/rain-water-drop-falling-city-street-floor-heavy-rain-day_1962-2005.jpg?w=2000",
//   },
// ]
